### ISSUE TITLE
Missing positional argument: 'layer_idx' when using QAlignVideoScorer

### ISSUE THREAD

**Issue by johind** [Q-Future/Q-Align#4]
Hey, i'm currently testing your model on some videos.

When running the following code

```python
import argparse
from q_align import QAlignVideoScorer, load_video

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-i", "--input", type=str, required=True)
    args = parser.parse_args()

    scorer = QAlignVideoScorer()

    video_list = [load_video(args.i)]

    score = scorer(video_list).tolist()

    print("Score:", score)

if __name__ == "__main__":
    main()
```

i encounter this error in the transformers codebase:

```shell
python video_inference.py -i ./example-video.mp4
Traceback (most recent call last):
  File "/experimental/video_inference.py", line 18, in <module>
    main()
  File "/experimental/video_inference.py", line 9, in main
    scorer = QAlignVideoScorer()
  File "/experimental/Q-Align/q_align/evaluate/scorer.py", line 121, in __init__
    tokenizer, model, image_processor, _ = load_pretrained_model(pretrained, None, "mplug_owl2", device=device)
  File "/experimental/Q-Align/q_align/model/builder.py", line 107, in load_pretrained_model
    model = AutoModelForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, **kwargs)
  File "/home/ubuntu/mambaforge/envs/q-align/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 493, in from_pretrained
    return model_class.from_pretrained(
  File "/home/ubuntu/mambaforge/envs/q-align/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2700, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/experimental/Q-Align/q_align/model/modeling_mplug_owl2.py", line 253, in __init__
    self.model = MPLUGOwl2LlamaModel(config)
  File "/experimental/Q-Align/q_align/model/modeling_mplug_owl2.py", line 245, in __init__
    super(MPLUGOwl2LlamaModel, self).__init__(config)
  File "/experimental/Q-Align/q_align/model/modeling_mplug_owl2.py", line 77, in __init__
    super(MPLUGOwl2MetaModel, self).__init__(config)
  File "/home/ubuntu/mambaforge/envs/q-align/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 561, in __init__
    self.layers = nn.ModuleList([LlamaDecoderLayer(config) for _ in range(config.num_hidden_layers)])
  File "/home/ubuntu/mambaforge/envs/q-align/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 561, in <listcomp>
    self.layers = nn.ModuleList([LlamaDecoderLayer(config) for _ in range(config.num_hidden_layers)])
TypeError: LlamaDecoderLayer.__init__() missing 1 required positional argument: 'layer_idx'
```

Do you happen to know what might cause this / how i can fix this? Thank you!

**Edit**:

Here is a list of my installed dependencies:

```txt
accelerate==0.21.0
aiofiles==23.2.1
aiohttp==3.9.1
aiosignal==1.3.1
altair==5.2.0
anyio==4.2.0
asttokens==2.4.1
async-timeout==4.0.3
attrs==23.2.0
bitsandbytes==0.41.0
certifi==2023.11.17
charset-normalizer==3.3.2
click==8.1.7
cmake==3.28.1
colorama==0.4.6
contourpy==1.2.0
cycler==0.12.1
decord==0.6.0
einops==0.6.1
einops-exts==0.0.4
exceptiongroup==1.2.0
executing==2.0.1
fastapi==0.108.0
ffmpy==0.3.1
filelock==3.13.1
fonttools==4.47.0
frozenlist==1.4.1
fsspec==2023.12.2
gradio==3.35.2
gradio_client==0.2.9
h11==0.14.0
httpcore==0.17.3
httpx==0.24.0
huggingface-hub==0.20.2
icecream==2.1.3
idna==3.6
Jinja2==3.1.2
joblib==1.3.2
jsonschema==4.20.0
jsonschema-specifications==2023.12.1
kiwisolver==1.4.5
linkify-it-py==2.0.2
lit==17.0.6
markdown-it-py==2.2.0
markdown2==2.4.12
MarkupSafe==2.1.3
matplotlib==3.8.2
mdit-py-plugins==0.3.3
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
networkx==3.2.1
numpy==1.26.3
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
orjson==3.9.10
packaging==23.2
pandas==2.1.4
peft==0.4.0
pillow==10.2.0
psutil==5.9.7
pydantic==1.10.13
pydub==0.25.1
Pygments==2.17.2
pyparsing==3.1.1
python-dateutil==2.8.2
python-multipart==0.0.6
pytz==2023.3.post1
PyYAML==6.0.1
-e git+https://github.com/Q-Future/Q-Align.git@59d293bf03a4ee4268af2f0c0dd64747572aa8a0#egg=q_align
referencing==0.32.1
regex==2023.12.25
requests==2.31.0
rpds-py==0.16.2
safetensors==0.4.1
scikit-learn==1.2.2
scipy==1.11.4
semantic-version==2.10.0
sentencepiece==0.1.99
shortuuid==1.0.11
six==1.16.0
sniffio==1.3.0
starlette==0.32.0.post1
svgwrite==1.4.3
sympy==1.12
threadpoolctl==3.2.0
timm==0.6.13
tokenizers==0.13.3
toolz==0.12.0
torch==2.0.1
torchvision==0.15.2
tqdm==4.66.1
transformers==4.31.0
triton==2.0.0
typing_extensions==4.9.0
tzdata==2023.4
uc-micro-py==1.0.2
urllib3==2.1.0
uvicorn==0.25.0
wavedrom==2.0.3.post3
websockets==12.0
yarl==1.9.4
```

**Comment by johind** [comment]
**Update** 

I've updated the transformers package to 4.36 and the error no longer occurs.

The model can now create a score, but throws UserWarnings. Can i ignore these warnings?

```shell
Instantiating LlamaAttention without passing `layer_idx` is not recommended and will to errors during the forward call, if caching is used. Please make sure to provide a `layer_idx` when creating this class.
Loading checkpoint shards: 100%|██████████████████| 2/2 [00:16<00:00,  8.13s/it]
/home/ubuntu/mambaforge/envs/q-align/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:389: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/home/ubuntu/mambaforge/envs/q-align/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:394: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
```

**Comment by teowu** [comment]
Yes, just ignore the warning. 
This is because the hacked mPLUG-Owl2 code does not pass this layer_idx, but no compromise on results.

Best
Haoning
