### ISSUE TITLE
KeyError: 'MPLUGOwl2Config'

### ISSUE THREAD

**Issue by MengHao666** [Q-Future/Q-Align#42]
Following your instruction, I run 

```
export DEFAULT_IMG_PATH=fig/baby.mp4
python q_align/evaluate/scorer.py --img_path $DEFAULT_IMG_PATH --video --model-path q-future/one-align

```

and I meet such error
```
Traceback (most recent call last):
  File "/Users/momiao/Desktop/Projects/Q-Align/q_align/evaluate/scorer.py", line 147, in <module>
    scorer = QAlignVideoScorer(pretrained=args.model_path, device=args.device)
  File "/Users/momiao/Desktop/Projects/Q-Align/q_align/evaluate/scorer.py", line 102, in __init__
    tokenizer, model, image_processor, _ = load_pretrained_model(pretrained, None, "mplug_owl2", device=device)
  File "/Users/momiao/Desktop/Projects/Q-Align/q_align/model/builder.py", line 106, in load_pretrained_model
    tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
  File "/Users/momiao/miniforge3/envs/q_align/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 803, in from_pretrained
    tokenizer_class_py, tokenizer_class_fast = TOKENIZER_MAPPING[type(config)]
  File "/Users/momiao/miniforge3/envs/q_align/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 737, in __getitem__
    model_type = self._reverse_config_mapping[key.__name__]
KeyError: 'MPLUGOwl2Config'
```

**Comment by MengHao666** [comment]
could anyone help  me about this question? Does this repo really have such good results as they claimed?

**Comment by MengHao666** [comment]
following code does not work either
```
import pyiqa
import torch

qalign = pyiqa.create_metric('qalign').cuda()
quality_score = qalign(input, task_='quality')
aesthetic_score = qalign(input, task_='aesthetic')
```

**Comment by trojblue** [comment]
did you try `pip install "transformers==4.36.1"`? I ran into the issue similar to [this](https://github.com/Q-Future/Q-Align/issues/31) and the solution there fixes it

**Comment by MengHao666** [comment]
> did you try `pip install "transformers==4.36.1"`? I ran into the issue similar to [this](https://github.com/Q-Future/Q-Align/issues/31) and the solution there fixes it

I tried but failed the same.

**Comment by xuchunyuan** [comment]
same error,do you fix ?

**Comment by MengHao666** [comment]
> same error,do you fix ?

can not fix, this repo is not available to pratical usage now
